[req]
default_bits = 2048                      # Размер ключа RSA
prompt = no                              # Не запрашивать ввод вручную — всё берётся из конфигурации
default_md = sha256                      # Хэш-функция для подписи
req_extensions = req_ext                 # Используемое расширение запроса
distinguished_name = dn                  # Секция с информацией о владельце сертификата

[dn]
C = RU                                   # Страна
ST = VoronezhOblast                      # Область
L = Voronezh                             # Город
O = VoronezhStateUniversity              # Организация
OU = CSF                                 # Подразделение
emailAddress = fatomartyr@gmail.com      # Email владельца
CN = task-service.local                  # Common Name (обычно домен сервиса)

[req_ext]
extendedKeyUsage = serverAuth            # Расширенное использование — TLS сервер
subjectKeyIdentifier = hash              # Идентификатор ключа
keyUsage = digitalSignature, nonRepudiation  # Разрешённые действия ключа
basicConstraints = CA:false              # Это не сертификат центра сертификации
subjectAltName = @alt_names              # Альтернативные имена

[alt_names]
DNS.1 = task-service.local               # Альтернативное доменное имя
IP.1 = 10.10.10.30                        # Альтернативный IP-адрес
