#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/server_cert

- name: Ensure certificate directory exists
  ansible.builtin.file:
    path: "{{ issued_cert_dir }}"
    state: directory
    mode: '0755'

- name: Copy CSR config
  ansible.builtin.copy:
    src: "{{ issued_cert_csr_config_src }}"
    dest: "{{ issued_cert_csr_config_dest }}"
    mode: '0644'

- name: Generate CSR via command
  ansible.builtin.shell:
    cmd: >
      openssl req -new -nodes
      -keyout {{ issued_cert_csr_keyout_path }}
      -out {{ issued_cert_csr_path }}
      -config {{ issued_cert_csr_config_dest }}
      -extensions req_ext
    creates: "{{ issued_cert_csr_path }}"

- name: Sign server certificate with Root CA
  community.crypto.x509_certificate:
    csr_path: "{{ issued_cert_csr_path }}"
    provider: ownca
    ownca_path: "{{ root_ca_cert_path }}"
    ownca_privatekey_path: "{{ root_ca_key_path }}"
    ownca_not_after: "{{ issued_cert_not_after }}"
    path: "{{ issued_cert_cert_path }}"
