-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-03-15 23:25:55 MSK
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE Advertisement 
    (
     id BIGINT NOT NULL , 
     text VARCHAR (500) NOT NULL , 
     displayOrder INTEGER NOT NULL , 
     displayId BIGINT , 
     companyName VARCHAR (100) , 
     companyINN VARCHAR (100) 
    )
GO

ALTER TABLE Advertisement ADD CONSTRAINT Advertisement__IDX PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Display 
    (
     id BIGINT NOT NULL , 
     currentTime DATETIME , 
     serialNumber BIGINT , 
     lastSyncTime DATETIME , 
     station VARCHAR (100) , 
     scheduleId BIGINT NOT NULL 
    )
GO

ALTER TABLE Display ADD CONSTRAINT Display__IDX PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Schedule 
    (
     id BIGINT NOT NULL , 
     lastUpdate DATETIME , 
     displayId BIGINT NOT NULL , 
     validFrom DATETIME , 
     validUntil DATETIME 
    )
GO

ALTER TABLE Schedule ADD CONSTRAINT Schedule__IDX PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Sensor 
    (
     id BIGINT NOT NULL , 
     active BIT , 
     serialNumber BIGINT , 
     modelName VARCHAR (100) 
    )
GO

ALTER TABLE Sensor ADD CONSTRAINT Sensor__IDX PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE SensorEvent 
    (
     id BIGINT NOT NULL , 
     sensorId BIGINT NOT NULL , 
     eventTime DATETIME NOT NULL , 
     eventType VARCHAR (20) NOT NULL 
    )
GO

ALTER TABLE SensorEvent ADD CONSTRAINT SensorEvent__IDX PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE TrainSchedule 
    (
     id BIGINT NOT NULL , 
     trainId BIGINT NOT NULL , 
     destinationStation VARCHAR (100) NOT NULL , 
     plannedArrival DATETIME NOT NULL , 
     plannedDeparture DATETIME NOT NULL , 
     scheduleId BIGINT NOT NULL 
    )
GO

ALTER TABLE TrainSchedule ADD CONSTRAINT TrainSchedule__IDX PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Violation 
    (
     id BIGINT NOT NULL , 
     type VARCHAR (20) NOT NULL , 
     actualTime DATETIME NOT NULL , 
     plannedTime DATETIME NOT NULL , 
     sensorEventId BIGINT NOT NULL , 
     trainScheduleId BIGINT NOT NULL , 
     displayId BIGINT NOT NULL 
    )
GO

ALTER TABLE Violation ADD CONSTRAINT Violation__IDX PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE Violation ADD CONSTRAINT Violation__UN UNIQUE NONCLUSTERED (sensorEventId)
GO

ALTER TABLE Advertisement 
    ADD CONSTRAINT Advertisement_Display_FK FOREIGN KEY 
    ( 
     displayId
    ) 
    REFERENCES Display 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Display 
    ADD CONSTRAINT Display_Schedule_FK FOREIGN KEY 
    ( 
     scheduleId
    ) 
    REFERENCES Schedule 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SensorEvent 
    ADD CONSTRAINT FK_ASS_1 FOREIGN KEY 
    ( 
     sensorId
    ) 
    REFERENCES Sensor 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE TrainSchedule 
    ADD CONSTRAINT TrainSchedule_Schedule_FK FOREIGN KEY 
    ( 
     scheduleId
    ) 
    REFERENCES Schedule 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Violation 
    ADD CONSTRAINT Violation_Display_FK FOREIGN KEY 
    ( 
     displayId
    ) 
    REFERENCES Display 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Violation 
    ADD CONSTRAINT Violation_SensorEvent_FK FOREIGN KEY 
    ( 
     sensorEventId
    ) 
    REFERENCES SensorEvent 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Violation 
    ADD CONSTRAINT Violation_TrainSchedule_FK FOREIGN KEY 
    ( 
     trainScheduleId
    ) 
    REFERENCES TrainSchedule 
    ( 
     id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

CREATE VIEW DisplayStatusView ( display_id, currentTime, destinationStation, elapsed_since_departure, schedule_version, status, current_ad ) AS
SELECT 
  d.id AS display_id,
  d.currentTime,
  ts.destinationStation,
  TIMESTAMPDIFF(MINUTE, MAX(se.eventTime), NOW()) AS elapsed_since_departure,
  s.lastUpdate AS schedule_version,
  d.status,
  a.text AS current_ad
FROM Display d
JOIN Schedule s ON d.id = s.id
JOIN TrainSchedule ts ON s.id = ts.id  
LEFT JOIN SensorEvent se ON ts.id = se.trainScheduleId AND se.eventType = 'DEPARTURE'
LEFT JOIN Advertisement a ON d.id = a.displayId
WHERE d.status = 'active'
  AND ts.plannedDeparture >= DATE_SUB(NOW(), INTERVAL 10 MINUTE)  -- Последние 10 мин
GROUP BY d.id, ts.destinationStation 
GO

CREATE VIEW ViolationReportView ( station_id, violation_date, type, violation_count, avg_delay_minutes, max_delay_minutes ) AS
SELECT 
  d.station_id,
  DATE(v.actualTime) AS violation_date,
  v.type,
  COUNT(*) AS violation_count,
  AVG(TIMESTAMPDIFF(MINUTE, v.actualTime, v.plannedTime)) AS avg_delay_minutes,
  MAX(TIMESTAMPDIFF(MINUTE, v.actualTime, v.plannedTime)) AS max_delay_minutes
FROM Violation v
JOIN SensorEvent se ON v.sensorEventId = se.id
JOIN Sensor s ON se.sensorId = s.id
JOIN Display d ON s.displayId = d.id  -- Сенсор → Табло → Станция
GROUP BY d.station_id, DATE(v.actualTime), v.type 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              2
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0